name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: windows
    steps:
      - run: echo "[Info] Conectando ao ssh..."
      - run: ssh ubuntu@app.dev.smartenergia.com.br
      - run: cd /var/www/frontend
      - run: git pull origin dev
      - run: yarn build
      - run: sudo systemctl daemon-reexec
      - run: sudo systemctl daemon-reload
      - run: sudo systemctl enable frontend
      - run: sudo systemctl start frontend
      - run: echo "[Info] Pull request enviado para o servidor de desenvolvimento."
      - run: echo "[Info] Repositório ${{ gitea.repository }} online para desenvolvimento."
      - run: echo "🍏 This job's status is ${{ job.status }}."